# Generated by Django 4.1.2 on 2022-10-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_completed_alter_todolist_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='completed',
        ),
    ]
