# Generated by Django 4.1.2 on 2022-10-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_todolist_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='completed',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
